### ISSUE TITLE
make calendar display today and the next 6 days

### ISSUE THREAD

**Issue by andrewarrow** [higherdotteam/mobischeduler#2]
Sunday Jan 22	Monday Jan 23	Tuesday Jan 24	Wednesday Jan 25	Thursday Jan 26	Friday Jan 27	Saturday Jan 28 is currently hard coded. make that look up today's date and make those strings programmatically.

**Comment by chrismomdjian** [comment]
resolved by looping dates and times to populate grid rather than hardcoding them
